import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";

const montserrat = Montserrat({
  display:"swap",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Header/>
        {children}
        <ToastContainer autoClose={3000}/>
      </body>
    </html>
  );
}
